# 管理窗口行为和工作区（虚拟桌面）的设置
############################################
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
############################################

# layerrule
layerrule = blur on, match:namespace logout_dialog

layerrule = blur on, match:namespace notifications
layerrule = blur_popups on, match:namespace notifications # mako的弹窗
layerrule = xray 1, match:namespace notifications

# windowrule = opacity 1.0 override, match:class Rofi # 禁用rofi的不透明度
layerrule = blur on, match:namespace rofi
layerrule = xray 1, match:namespace rofi
layerrule = ignore_alpha 0, match:namespace rofi # 解决rofi边角的透明度问题
layerrule = blur_popups on, match:namespace rofi


# windowrule = fullscreenstate 2 1, match:class chromium # 强制应用全屏

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
